export const API_URL = 'https://worker-production-46ee.up.railway.app';

export const Colors = {
  bg: '#06060F',
  surface: '#0D0D1A',
  surface2: '#13132A',
  border: 'rgba(124,111,247,0.10)',
  borderHi: 'rgba(124,111,247,0.22)',
  purple: '#7C6FF7',
  purpleDim: 'rgba(124,111,247,0.14)',
  green: '#4ADE80',
  red: '#F87171',
  orange: '#FB923C',
  blue: '#60A5FA',
  text: '#EEEDF8',
  muted: 'rgba(238,237,248,0.48)',
  dim: 'rgba(238,237,248,0.20)',
};

export const ENDPOINTS = {
  REGISTER: '/api/mobile/register',
  SEND_OTP: '/api/mobile/send_otp',
  VERIFY_OTP: '/api/mobile/verify_otp',
  RECOVER_ACCOUNT: '/api/mobile/recover_account',
  CHAT: '/api/mobile/chat',
  VOICE_QUERY: '/api/mobile/voice_query',
  DASHBOARD: '/api/mobile/dashboard',
  PROFILE: '/api/mobile/profile',
  WIKI: '/api/mobile/wiki',
  FEED: '/api/mobile/feed',
  CONVERSATION: '/api/mobile/conversation',
  MESSAGES: '/api/mobile/messages',
  GUARD_FULL: '/api/mobile/guard/full',
  ACTIONS: '/api/mobile/actions',
  REMEMBER: '/api/mobile/remember',
  BRIEF: '/api/mobile/brief',
  EVENING: '/api/mobile/evening',
  PUSH_TOKEN: '/api/mobile/push_token',
  CHECKIN: '/api/mobile/checkin',
  RITUAL_QUESTIONS: '/api/mobile/ritual/questions',
  RITUAL_ANSWER: '/api/mobile/ritual/answer',
  CHANGELOG: '/api/mobile/changelog',
  PRIVACY_SUMMARY: '/api/mobile/privacy/summary',
  PRIVACY_CLEAR: '/api/mobile/privacy/clear',
  CONFIG: '/api/mobile/config',
} as const;
